apiVersion: apps/v1
kind: Deployment
metadata:
  name: depilace-v-praze
  namespace: instalater24
spec:
  restartPolicy: OnFailure
  replicas: 1
  selector:
    matchLabels:
      app: depilace-v-praze
  template:
    metadata:
      labels:
        app: depilace-v-praze
    spec:
      containers:
      - name: depilace-v-praze
        image: localhost:32000/depilace-v-praze:latest
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: depilace-v-praze
  namespace: instalater24
spec:
  selector:
    app: depilace-v-praze
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: depilace-v-praze-ingress
 annotations:
  cert-manager.io/cluster-issuer: lets-encrypt
spec:
 tls:
 - hosts:
   - depilace-v-praze.cz
   secretName: depilace-v-praze-ingress-tls
 rules:
 - host: depilace-v-praze.cz
   http:
     paths:
     - backend:
         service:
           name: depilace-v-praze
           port:
             number: 80
       path: /
       pathType: Prefix
